language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "QBmi8Gg5ScHllefLdR/BLKnWiHaiWeTvPSfr18lgo2t7fd0qxUMBDHsrtNleOhO2kjGYfIgVtjcpJXeVLMPgnf9LVW9xKq9wcT3rgxnEWRosm073sjqRm2wmug2h16xaPPk8Ry+rxgwfiYRrild4JfH7chvHWv00titV32Fv1Dr3Kj7uqoVBl1bRTnri5UA7yxDlKG2MAgfv9M0SH2XRcSTVjSHxfUJB5JJuF6IEazvmA+eYmVDxOw3LI2fK95k+CDaRHS7wufjdsSkIQHRff+2QNdRxIHNoydwWRd343U2reatH5KEKpXxJQ8p1urq62ylL5ORcKF9cMrND0dFppseFOrhgq4CuKCxg9b01S3BxMhW6BdQ43+nTtd41alcdtqpU5zL/5bgsciWNrFeDcVj+fvdODEcDUvAphyBDAVp0OfhwVDvIl0tX9oYFXBQ2U7mWuZa3j4CbB6Ni8yPgiF5RYjIvQECd1gyV84FioocBb59/QmGCKPi1NEfRbQpqAL/a09az0nXDrGFSdUGvb9CgQspo3EKDZB9ItOJunkYuboOHdMMWBv+8lRthfSg671JTl00NyglLdHGeSHmkc9olm6Qjtn3BbWw2h4XAllyQIx/rjTREmjGlsu+wgDN52LBWSeGEhvRFKc1HxRJZG4SKSSfJvIkUlmDt9UA6l8c=QBmi8Gg5ScHllefLdR/BLKnWiHaiWeTvPSfr18lgo2t7fd0qxUMBDHsrtNleOhO2kjGYfIgVtjcpJXeVLMPgnf9LVW9xKq9wcT3rgxnEWRosm073sjqRm2wmug2h16xaPPk8Ry+rxgwfiYRrild4JfH7chvHWv00titV32Fv1Dr3Kj7uqoVBl1bRTnri5UA7yxDlKG2MAgfv9M0SH2XRcSTVjSHxfUJB5JJuF6IEazvmA+eYmVDxOw3LI2fK95k+CDaRHS7wufjdsSkIQHRff+2QNdRxIHNoydwWRd343U2reatH5KEKpXxJQ8p1urq62ylL5ORcKF9cMrND0dFppseFOrhgq4CuKCxg9b01S3BxMhW6BdQ43+nTtd41alcdtqpU5zL/5bgsciWNrFeDcVj+fvdODEcDUvAphyBDAVp0OfhwVDvIl0tX9oYFXBQ2U7mWuZa3j4CbB6Ni8yPgiF5RYjIvQECd1gyV84FioocBb59/QmGCKPi1NEfRbQpqAL/a09az0nXDrGFSdUGvb9CgQspo3EKDZB9ItOJunkYuboOHdMMWBv+8lRthfSg671JTl00NyglLdHGeSHmkc9olm6Qjtn3BbWw2h4XAllyQIx/rjTREmjGlsu+wgDN52LBWSeGEhvRFKc1HxRJZG4SKSSfJvIkUlmDt9UA6l8c="
jdk:
- oraclejdk8
script:
- ./gradlew sonarqube
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle
notifications:
  email: false
