language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "wJTjazDA7KC9VbjOeTSDDznlj1yCYyioC/CdAZAvA8s3xl6i+IfgGB62+FE/xq8YXFoSU6vYJIoZLkJXihj2HsPmeQ4NbFcg28n+eQbXu7v5AJTRmRB0nH/OZI6cbh7As6DhQmVxPezeRIln1IxyG84A55FoTREjNgXIUySHj1uHBPgvtHTe+0IJQqGiNtnVBaqYdtj7OuIi9FZIUJck2FdYcNzLINsA3rvvmvZ69OlOjO1GaxqbbpQzxV15OTlD3Aa95+3XyvEAguha/EyXt0oDY4TCMsZYBK5VlgB6MzE3GmU6bQb16PIjXcjW8f9QpvB3cycQxMsU2wD3QfczuqtTDoFFQa2fFkkq/nPTdMK88qYGfa8wXP44rNk+f6j7+Xkd0jg+qyZMpWGEi8mXocvjA3OhBhJc1dJLtC7zFD2vAwmpkvQaVXrqZWkpS3m54aSk/0e4ksviepc+s/NjiHGPqqDYYeP37SWbmKPvah3W5HwBs90mpyBiNGhn9LP7+tVLf2cwXrB9F8vSfBP3gCaaOyennZJmwnPdv2GrYrWsv/vtGC86Kg55ELyveLwS9Smh6yfwk3nRiOGNXHq7+ICzgYIHRgt+0SLLl/4X3Cis+y1v3RFHe9GKyDY4CWC/65eqs2IMfkYG9XlMy5RBNKcqMkeAeNfjl53uwd++rUc="
jdk:
- oraclejdk8
script:
- ./gradlew sonarqube -Dsonar.host.url=http://163.172.129.11:59000
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle
notifications:
  email: false
